site_name: SiteWorks API Documentation
nav:
  - Home: index.md
  - Introduction:
      - What is SiteWorks API?: introduction/product.md
      - Licensing Model: introduction/license.md
      - About our ompany: introduction/company.md
      - Documentation project: introduction/project.md
  - API Docs:
      - API Authentication: api-docs/api-authentication.md
      - API Endpoints Swagger: api-docs/api-endpoints.md
      - API Features: api-docs/api-features.md
      - Use Cases: api-docs/api-use-cases.md
      - Error Handling: api-docs/error-handling.md
      - FAQ: api-docs/api-faq.md
  - Developer Guide:
      - Roadmap: product-docs/roadmap.md
      - Release Notes: product-docs/release-notes.md
      - Changelog: product-docs/changelog.md
  - System Docs:
      - API Architecture: system-docs/api-architecture.md
      - API Tech Stack: system-docs/api-tech-stack.md
  - Annex:
      - Glossary references: annex/glossary-references.md
theme:
  name: readthedocs
  user_color_mode_toggle: true
  locale: en
  logo: images/logo.png
plugins:
  - swagger-ui-tag
  - search
  - mermaid2
